### ISSUE TITLE
requests take 55s ?

### ISSUE THREAD

**Issue by ericb-summit** [Spaced-Out/ecs-container-exporter#7]
Not sure how active this project is, but can anyone thing of a reason why metrics requests take 55 seconds to complete?

Systematically, 55 seconds every time.  Which obviously times out on the prometheus side.

curl'ing the metadata endpoint seems to provide a response instantly.  The logs show nothing useful.

Thanks

**Comment by raags** [comment]
It’s because of this https://github.com/Spaced-Out/ecs-container-exporter#metrics

Increase the scrape timeout to 1m

**Comment by mritalian** [comment]
Yeah that's what I was afraid of.  Thanks.

**Comment by raags** [comment]
Its configurable with `--interval`

**Comment by ericb-summit** [comment]
Thanks, will look into it.
